### ISSUE TITLE
botの履歴を取る

### ISSUE THREAD

**Issue by smicle** [beroba/convex-management#431]
- [x] 履歴チャンネルの作成とid取得
  - [x] #bot操作-履歴
  - [x] #1ボス-凸宣言-履歴
  - [x] #2ボス-凸宣言-履歴
  - [x] #3ボス-凸宣言-履歴
  - [x] #4ボス-凸宣言-履歴
  - [x] #5ボス-凸宣言-履歴
  - [x] #持越状況-履歴
  - [x] #凸予定-履歴
  - [x] #凸状況-履歴
  - [x] #ボス状況-履歴

以下の項目が独立して変更され次第履歴を残す
- bot操作
  - [x] 凸状況の変更
  - [x] 活動限界時間の変更
  - [x] タスキル状態の変更
  - [x] 離席中状態の変更
- 凸宣言
  - [x] 凸宣言
  - [x] ダメージ集計
  - [x] コマンド実行者
    - [x] 通しの通知
    - [x] ダメージ計算から除外
    - [x] ダメージ報告を削除
    - [x] ランダム選択
    - [x] 持越秒数計算
    - [x] HP変更
    - [x] 周回数を変更
- 持越状況
  - [x] メッセージの送信
- 凸予定
  - [x] 凸予定一覧
- 凸状況
  - 以下3つは連動して履歴を残す
  - [x] 全体状況
  - [x] 凸残状況
  - [x] 持越状況
- ボス状況
  - [x] ボス状況

**Comment by smicle** [comment]
ボス状況を凸状況の更新から分離する

**Comment by smicle** [comment]
確定や周回数変更のコマンド実行者も表示
